### PR TITLE
XP Bar Colors

### PR DESCRIPTION
**Pull request by MystWraith**
This is interesting.

Right now the current result looks like this:
image

### CODE REVIEW

**Comment by MystWraith** [comment]
# Game Plan
- [x] Suit Charge -> Yellow
- [x] Depth -> Match Bossbar
- [x] Radiation -> Default
  - [ ] Green?
- [ ] O2?
  - [ ] Add O2
  - [ ] O2 -> Light Blue

**Comment by MystWraith** [comment]
image
image

Examples of results (display level not needed, just serving as example)

**Comment by showierdata9978** [comment]
The bossbar thing is a DF issue

**Comment by MystWraith** [comment]
Ah, such as the missing radiation? I understand how the "depth" being present as a DF problem, but I'm not sure about the radiation issue

**Comment by showierdata9978** [comment]
Ye, DF broke bossbars xd (although we can patch around it for depth)

**Comment by MystWraith** [comment]
I'm sure. I have been using the `rel_spawn` value simply because it works better

**Comment by showierdata9978** [comment]
https://discord.com/channels/864581314296807424/1149043637502615662/1149043637502615662

**Comment by MystWraith** [comment]
Dnag, so that's what the server restart did... rip

**Comment by MystWraith** [comment]
Due to the DF weirdness, I have to delay this for a while

**Comment by MystWraith** [comment]
Just a question though, is this actually a good suggestion? I mean, I get to learn a ton about mods, but I dunno if people would even like this

**Comment by showierdata9978** [comment]
ye this allows you to tell what it is at a glance

**Pull request merged**
