### PR TITLE
Added Hide Plot Ads

### PR DESCRIPTION
**Pull request by MystWraith**
Just what it sounds like, matches plot ad messages and hides them.

Has an option to toggle on and off, defaults to on.

### CODE REVIEW

**Comment by MystWraith** [comment]
Uses depreciated/unused mixin, so does not technically work, but can be if the mixin is enabled.

**Comment by showierdata9978** [comment]
I still would not merge this; as i need to delete that code or fix the /locate functionality
( I Just cant figure the regexes out)

**Comment by MystWraith** [comment]
Regex works now. You can get the plot location and information. But I would recommend using `CodeClient` instead. They are a robust system for this anyway, and it doesn't use the locate command.

**Comment by MystWraith** [comment]
Or, I can use the `Event` I used in the previous iteration to get what location the player is in with a similar method to `CodeClient` but a little bit less crazy.

**Comment by MystWraith** [comment]
Never mind, I cannot do an equivalent thing as `CodeClient` with my current setup, but you could have use `CodeClient` as a dependency and use it's events.

**Pull request merged**
