### PR TITLE
Time until moon door

### LINKED ISSUE #43: Time until moon door
add ui element on the side of the screen that shows the time until moon door is ready based on d/n cycle and/or time since last moon door

Also maybe add a togglable alarm/title for when moon door is ready/ready soon

### PR DESCRIPTION
**Pull request by MystWraith**
I need to see when the specific time when the moon door opens so I can get the difference.

This is in solution to #43

image

The number to the side is the time of day (in ticks-ish) that the message is sent.
I want to use this to get the time the 'The moon door has opened' message is sent.

### CODE REVIEW

**Comment by MystWraith** [comment]
Mostly I just need style suggestions. Like, should I just have it follow the `CCT` like I already have? Should I have the `NOW` feature that I do?
image

**Comment by showierdata9978** [comment]
Btw check both settings, im not sure thatl work

**Comment by MystWraith** [comment]
I mean, they switch when you go the the bottom corner, is that wrong?

**Comment by showierdata9978** [comment]
I did not know what it would do lol; but yeah that's fine.

That setting is really only for my workflow lol (my top is alr taken by
fps, and outside of pickaxe, chords)

**Comment by showierdata9978** [comment]
Fabulously optimised compatibly stuff

**Comment by MystWraith** [comment]
Lol, so should I separate it out into different settings? I don't see a ton of use from that, but I dunno.

**Comment by showierdata9978** [comment]
No its fine; i just meant that its my personal game preference lol

**Comment by MystWraith** [comment]
~~Feel free to change it if you want~~
EDIT: I added a way to switch it if you want :)

**Comment by MystWraith** [comment]
Now all I need to do is make a sound effect for when the door activates, if needed

**Comment by MystWraith** [comment]
I haven't tested this yet, I'll do it tomorrow. It's late where I am rn.

**Comment by showierdata9978** [comment]
Its 1:50Am for me lol

**Comment by MystWraith** [comment]
You're two hours ahead of me lol

**Comment by MystWraith** [comment]
It's not working, I gotta work on that

**Comment by showierdata9978** [comment]
~Oh btw the reason it ticks by that amount is, a pickaxe day-night cycle is \~11.5 minutes long according to acod~

**Comment by MystWraith** [comment]
Eh, no, sorry. Its ~15 mins
It's 14.2857143 minutes long
Or roughly 14 mins 17 seconds

**Comment by MystWraith** [comment]
It's 14.2857143 minutes long

**Comment by MystWraith** [comment]
Or roughly 14 mins 17 seconds

**Comment by showierdata9978** [comment]
~And thats why i couldn't get my moon door impl to work lol, acod gave me
wrong information~

**Comment by MystWraith** [comment]
Lol, that's why I did it the way that I did, I wouldn't have to crunch any numbers by hand, I could just get the moon door time and have the computer do it

**Comment by showierdata9978** [comment]
I checked your work, its a tiny bit off by like .1

`
24000 / (14.2857143 * 60)
`

Its fine tho

**Comment by MystWraith** [comment]
All I did was `24000 / 28 / 60`, then took the decimal place (rounded to 7 places) and multiplied it by 60
It's a rounding error
`24000 / 14.2857143 / 60` should get you exactly 28 (with minor rounding).
I literally used a calculator, and I just double checked. I'm not wrong.

On top of that, that's not how I calculate the time until moon door anyway!

**Comment by showierdata9978** [comment]
I mean i checked what the TPS was

**Comment by showierdata9978** [comment]
Thats what that does

**Comment by MystWraith** [comment]
I used logs to get timestamps and made every message have a note that says the current time of day and saw the consistent 28 increase over 1 second (never any smaller increments, I tested). Yes, TPS can fluctuate, but that's a server problem and is not intrinsic to Pickaxe alone.

**Comment by showierdata9978** [comment]
Ye ik, that's just the constant that I did i wont close/deny your PR for it

**Comment by MystWraith** [comment]
Now I don't even know what exactly you are talking about. I thought I understood, but now I don't.

**Comment by showierdata9978** [comment]
Im also kinda tired rn, im in the class right before lunch for me, and i
have the last lunch

**Comment by MystWraith** [comment]
Only issue is that it will not work outside of Pickaxe, it technically could, but it has an issue that it does not start "enabled" like the CCT, but I guess technically possible, but only after the player goes to pickaxe at least once.

**Comment by MystWraith** [comment]
Another note is that the sounds need to be fine tuned

**Comment by MystWraith** [comment]
The sounds aren't quite right. The `NOW` sound doesn't play.

**Pull request merged**
