### PR TITLE
Auto gg

### PR DESCRIPTION
**Pull request by MystWraith**
This was suggested by me in #16.

I added a option to toggle it on and off, defaults to off.

### CODE REVIEW

**Comment by MystWraith** [comment]
Uses depreciated/unused mixin, so does not technically work, but can be if the mixin is enabled.

**Comment by MystWraith** [comment]
I forgot to check if the player is in pickaxe, so this is not ready yet.

**Comment by showierdata9978** [comment]
I still would not merge this; as i need to delete that code or fix the /locate functionality 
( I Just cant figure the regexes out)

**Comment by MystWraith** [comment]
I can look into it if you want. I have to do a bunch of regex anyway

**Comment by showierdata9978** [comment]
Also this probably counts as a bot

**Comment by MystWraith** [comment]
Kinda I guess? It's an auto response, I don't know if that counts as a bot. Maybe? And I don't know if those are illegal.

**Comment by showierdata9978** [comment]
> Kinda I guess? It's an auto response, I don't know if that counts as a bot. Maybe? And I don't know if those are illegal.

You have too get explicit admin permission to make bots on DF lol

Check pins in #dfchat if you want to see it sent by jere

**Comment by MystWraith** [comment]
I checked the rules, and it is not allowed to send anything in public chat. So the answer is no-- this option is not allowed on df (though it basically exists by tradition anyway)

**Comment by MystWraith** [comment]
Luckly it didn't work anyway

**Pull request closed without merging**
