### PR TITLE
Weird Bar

### PR DESCRIPTION
**Pull request by MystWraith**
Just gets rid of it.

### CODE REVIEW

**Comment by showierdata9978** [comment]
This does nothing?

i dont see any changes

**Comment by showierdata9978** [comment]
plus it has conflicts anyways

**Comment by MystWraith** [comment]
Eh it's all good its the bar on the chat thing, it has to do with chat security, and it can be annoying to see it just randomly appear and disappear. All good tho

**Comment by showierdata9978** [comment]
Ah that's why i did not see it

Meh most ppl use no chat reports

**Pull request closed without merging**
