### PR TITLE
chest cooldown timer

### PR DESCRIPTION
**Pull request by HappyNBoy**
yes it's real the long awaited chest cooldown timer

i didn't actually test if it works after transferring the code to pickaxe mod-

### CODE REVIEW

**Comment by HappyNBoy** [comment]
i forgot to add some parenthesis AAA pain

**Comment by HappyNBoy** [comment]
oh wait it was a bunch of other things tabnine did a big oops

**Comment by showierdata9978** [comment]
small nitpick

Testing env
image

main env
image

**Comment by HappyNBoy** [comment]
weird, for me it works perfectly fine (just tested), check console or try disabling other mods you're using

**Comment by showierdata9978** [comment]
> weird, for me it works perfectly fine (just tested), check console or try disabling other mods you're using

oh sry, i meant that it would overlap with my FPS counter

**Pull request merged**
