### PR TITLE
Added Forge Timer UI Element

### PR DESCRIPTION
**Pull request by MystWraith**
A simple addition to the mod. I followed the suggestion in #9.

I plan on adding an Enum to the options to allow for changes in the UI placement.

### CODE REVIEW

**Review by showierdata9978 — CHANGES_REQUESTED** [review]
Separate into second function

**Comment by MystWraith** [comment]
I previously used the same function to reduce repeated work, but I changed it per request

**Comment by MystWraith** [comment]
Sorry renamed the branch and moved the default branch for personal repo management.

**Comment by showierdata9978** [comment]
you forgot to remove it from the drawCoins after moving it over

**Comment by MystWraith** [comment]
Fixed it! Sorry about that

**Comment by showierdata9978** [comment]
can you add Forge: To the front (white)

**Comment by showierdata9978** [comment]
might need to do 2 draw calls for that

**Comment by MystWraith** [comment]
I will yeah, but I think I can. I mean, we already get the width, so I think I can do that.

**Comment by MystWraith** [comment]
Tag added!

**Pull request merged**
